bigcorp/bigcorp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('email/', include(email_urls), name='email_verification'),
    path('', views.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bigcorp/cart/urls.py
from django.urls import path
from .views import cart_view, cart_add, cart_update, cart_delete

app_name = 'cart'

urlpatterns = [
    path('', cart_view, name='cart_view'),
    path('add/', cart_add, name='add_to_cart'),
    path('delete/', cart_delete, name='delete_from_cart'),
    path('update/', cart_update, name='update_to_cart'),
]

bigcorp/payment/urls.py
from .views import shipping, checkout, complete_order, payment_success, payment_fail, admin_order_pdf
from django.urls import path
from .webhooks import stripe_webhook

app_name = 'payment'

urlpatterns = [
    path('shipping/', shipping, name='shipping'),
    path('checkout/', checkout, name='checkout'),
    path('complete-order', complete_order, name='complete_order'),
    path('payment-success/', payment_success, name='payment_success'),
    path('payment-fail/', payment_fail, name='payment_fail'),
    path('webhook-stripe/', stripe_webhook, name='webhook_stripe'),
    path("order/<int:order_id>/pdf/", admin_order_pdf, name="admin_order_pdf"),
]

bigcorp/cart/models.py
from django.db import models

# Create your models here.

bigcorp/cart/views.py
from django.shortcuts import render, get_object_or_404

from cart.cart import Cart
from shop.models import ProductProxy
from django.http import JsonResponse


def cart_view(request):
    cart = Cart(request)

    context = {
        'cart': cart
    }
    return render(request, 'cart/cart_view.html', context=context)


def cart_add(request):
    """
    Add a product to the cart and return a JSON response with the updated cart quantity and the product title.

    Parameters:
    - request: HttpRequest object containing the POST data with 'action', 'product_id', and 'product_qty' fields.
    """
    cart = Cart(request)

    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('product_qty'))
        product = get_object_or_404(ProductProxy, id=product_id)
        cart.add(product=product, quantity=product_qty)
        cart_qty = cart.__len__()

        response = JsonResponse({'cart_qty': cart_qty, 'product': product.title})
        return response


def cart_update(request):
    """
    Update the quantity of a product in the cart and return a JSON response with the updated cart quantity and total price.

    Parameters:
    - request: HttpRequest object containing the POST data with 'action', 'product_id', and 'product_qty' fields.
    """
    cart = Cart(request)

    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        product_qty = int(request.POST.get('product_qty'))
        product = get_object_or_404(ProductProxy, id=product_id)
        cart.update(product=product, quantity=product_qty)
        cart_qty = cart.__len__()
        cart_total = cart.get_total_price()

        response = JsonResponse({'cart_qty': cart_qty, 'cart_total': cart_total})
        return response


def cart_delete(request):
    """
    Delete a product from the cart and return a JSON response with the updated cart quantity and total price.

    Parameters:
    - request: HttpRequest object containing the POST data with 'action' and 'product_id' fields.
    """
    cart = Cart(request)

    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('product_id'))
        product = get_object_or_404(ProductProxy, id=product_id)
        cart.delete(product=product)
        cart_qty = cart.__len__()
        cart_total = cart.get_total_price()

        response = JsonResponse({'cart_qty': cart_qty, 'cart_total': cart_total})
        return response

bigcorp/cart/templates/cart/cart_view.html
{% include "base.html" %} {% load static %} {% load mathfilters %} {% block content %}

<main class="pt-5">
    <div class="container">
        <h1 class="h5">Shopping cart</h1>

        <hr/>

        {% for item in cart %}
        {% with product=item.product %}

        <br/>

        <div class="row mb-4 border product-item">
            <div class="col-md-3 col-lg-2 order-md-first bg-light">
                <img
                        class="img-fluid mx-auto d-block"
                        width="200px"
                        alt="Responsive image"
                        src="{{product.image.url}}"
                />
            </div>

            <div class="col-md-9 col-lg-10 ps-md-3 ps-lg-10">
                <a
                        href="{{product.get_absolute_url}}"
                        class="text-info text-decoration-none"
                >
                    <h1 class="h5 pt-2">{{product.title}}</h1>
                </a>

                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">{{product.title}}</div>

                            <div class="col-6 text-end">
                                <span class="h6 fw-bold">$ {{product.price|mul:item.quantity }}</span>
                            </div>
                        </div>
                    </div>

                    <div class="col">
                        <div class="row p-3">
                            <div class="col-12">
                                <label for="select">Qty</label>

                                &nbsp;

                                <select id="select{{product.id}}">
                                    <option selected>{{item.quantity}}</option>

                                    <option value="1">1</option>

                                    <option value="2">2</option>

                                    <option value="3">3</option>

                                    <option value="4">4</option>
                                </select>

                                <br/>
                                <br/>

                                <button
                                        type="button"
                                        data-index="{{product.id}}"
                                        class="btn btn-primary btn-sm update-button"
                                >
                                    Update
                                </button>

                                &nbsp;

                                <button
                                        type="button"
                                        class="btn btn-danger btn-sm delete-button"
                                        data-index="{{product.id}}"
                                >
                                    Delete
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% endwith %}
        {% endfor %}

        <div class="col-12 text-end">
            <div class="h6 fw-bold">
                Total: $
                <div id="total" class="d-inline-flex">
                {{cart.get_total_price}}
                </div>
            </div>
                <button
                  type="button"
                  class="btn btn-success btn-md text-bg-light mt-4"

                >
                <a class="nav-link text-decoration-none" href="{% url 'payment:checkout' %}">Checkout</a>
                </button>
        </div>
    </div>

    <br/>
    <br/>
</main>

<script>

    $(document).on('click', '.delete-button', function(e){
      e.preventDefault();
      var index = $(this).data('index');
      $.ajax({
        url: '{% url 'cart:delete_from_cart' %}',
        type: 'POST',
        data: {
          product_id: $(this).data('index'),
          csrfmiddlewaretoken: '{{csrf_token}}',
          action: 'post'
        },
        success: function(response){
          document.getElementById('lblCartCount').textContent = response.quantity
          document.getElementById('total').textContent = response.total

          location.reload()
        },
        error: function(error){
          console.log(error)
        }
      })
    })

    $(document).on('click', '.update-button', function(e){
      e.preventDefault();

      var product_id = $(this).data('index');

      $.ajax({
        url: '{% url 'cart:update_to_cart' %}',
        type: 'POST',
        data: {
          product_id: $(this).data('index'),
          product_qty: $('#select' + product_id + ' option:selected').text(),
          csrfmiddlewaretoken: '{{csrf_token}}',
          action: 'post'
        },
        success: function(response){
          document.getElementById('lblCartCount').textContent = response.qty
          document.getElementById('total').textContent = response.total

          location.reload()
        },
        error: function(error){
          console.log(error)
        }
      })
    })
</script>

{% endblock %}