bigcorp/account/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.shortcuts import render
from .views import register_user_view, login_user_view, logout_user_view, dashboard_view, profile_view, \
    delete_users_view

app_name = 'account'

urlpatterns = [
    # register user
    path('register/', register_user_view, name='register'),
    path('email_verification/',
         lambda request: render(request, 'account/email/email_verification.html'),
         name='email_verification'),

    # login user
    path('login/', login_user_view, name='login'),
    path('logout/', logout_user_view, name='logout'),

    # dashboard
    path('dashboard/', dashboard_view, name='dashboard'),
    path('profile-management/', profile_view, name='profile_management'),
    path('delete-users/', delete_users_view, name='delete_user'),

    # password reset
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='account/password/password_reset.html',
             email_template_name='account/password/password_reset_email.html',
             success_url=reverse_lazy('account:password_reset_done')),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetView.as_view(
        template_name='account/password/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='account/password/password_reset_confirm.html',
             success_url=reverse_lazy('account:password_reset_complete')),
         name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='account/password/password_reset_complete.html'),
         name='password_reset_complete'),
]

bigcorp/bigcorp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_email_verification import urls as email_urls

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shop.urls', namespace='shop')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('email/', include(email_urls), name='email_verification'),
    path('', views.index, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bigcorp/cart/urls.py
from django.urls import path
from .views import cart_view, cart_add, cart_update, cart_delete

app_name = 'cart'

urlpatterns = [
    path('', cart_view, name='cart_view'),
    path('add/', cart_add, name='add_to_cart'),
    path('delete/', cart_delete, name='delete_from_cart'),
    path('update/', cart_update, name='update_to_cart'),
]

bigcorp/shop/urls.py
from django.urls import path
from .views import products_view, product_detail_view, category_list_view

app_name = 'shop'

urlpatterns = [
    path('', products_view, name='products'),
    path('<slug:slug>/', product_detail_view, name='product_detail'),
    path('category/<slug:category_slug>/', category_list_view, name='category_list'),
]

bigcorp/shop/models.py
import string
import random

from django.db import models
from django.urls import reverse
from django.utils.text import slugify


def rand_slug():
    """
    Generate a random slug for a category or product.

    Returns:
    str: A randomly generated slug consisting of lowercase letters and digits.
    """
    return ''.join(random.choice(string.ascii_lowercase + string.digits) for _ in range(3))


class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name='Категория')
    parent = models.ForeignKey(
        'self', on_delete=models.CASCADE, blank=True, related_name='children', null=True
    )
    slug = models.SlugField(max_length=200, unique=True, null=False, editable=True, verbose_name='Ссылка')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

        # prevent duplicate keys in database
        unique_together = ('slug', 'parent')

    def __str__(self):
        """
        Return a string representation of the Category instance.
        """
        full_path = [self.name]
        k = self.parent
        # print all the ancestors of the category
        while k is not None:
            full_path.append(k.name)
            k = k.parent
        return ' -> '.join(full_path[::-1])

    def save(self, *args, **kwargs):
        """
        Save method for the Category model.

        If the slug is not specified, it creates a slug from the name using a random string and the name.
        """
        if not self.slug:
            self.slug = slugify(rand_slug() + '-pickBetter' + self.name)

        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('shop:category_list', args=(self.slug,))


class Product(models.Model):
    category = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='products',
                                 verbose_name='Категория')
    title = models.CharField(max_length=200, verbose_name='Название товара')
    brand = models.CharField(max_length=200, verbose_name='Бренд', blank=True, null=True)
    description = models.TextField(blank=True, verbose_name='Описание')
    slug = models.SlugField(max_length=200, unique=True, null=False, editable=True, verbose_name='Ссылка')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    image = models.ImageField(upload_to='products/products/%Y/%m/%d', verbose_name='Изображение')
    available = models.BooleanField(default=True, verbose_name='Наличие')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=(self.slug,))


class ProductManager(models.Manager):
    def get_queryset(self):
        """
        Returns a queryset containing only the available products.

        Parameters:
        self: ProductManager instance

        Returns:
        queryset: A queryset containing only the available products.
        """
        return super(ProductManager, self).get_queryset().filter(available=True)


class ProductProxy(Product):
    objects = ProductManager()

    class Meta:
        proxy = True

bigcorp/shop/views.py
from django.shortcuts import render, get_object_or_404

from .models import Category, ProductProxy


def products_view(request):
    products = ProductProxy.objects.all()
    context = {
        'products': products,
    }
    return render(request, 'shop/products.html', context)


def product_detail_view(request, slug):
    product = get_object_or_404(ProductProxy, slug=slug)
    context = {
        'product': product,
    }
    return render(request, 'shop/product_detail.html', context)


def category_list_view(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    products = ProductProxy.objects.filter(category=category)
    context = {
        'category': category,
        'products': products,
    }
    return render(request, 'shop/category_list.html', context)

bigcorp/shop/templates/shop/category_list.html
{% extends "base.html" %}

{% load static %}


{% block content %}


<main>

  <div class="album py-5 bg-light">
    <div class="container">

      <div class="pb-3 h5"> {{category.name|capfirst}} </div>


      <hr>

      <br>


      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

      {% for product in products %}

        <div class="col">
          <div class="card shadow-sm">
          <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">

            <div class="card-body">
              <p class="card-text">
                <a class="text-info text-decoration-none" href="{{product.get_absolute_url}}">
                  {{ product.title|capfirst|slice:":50"|safe }} </a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <h5> $ {{product.price}} </h5>
              </div>
            </div>
          </div>
        </div>

       {% endfor %}

      </div>
    </div>
  </div>


</main>

{% endblock %}

bigcorp/shop/templates/shop/product_detail.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="container">

    <main class="pt-5">

        <div class="row g-3">

            <div class="col-md-5 col-lg-5 order-md-first bg-light">

                <img class="img-fluid mx-auto d-block" alt="Responsive image" src="{{product.image.url}}"> <!-- Product image -->

            </div>

            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">

                <h1 class="mb-0 h4"> {{product.title}}</h1>

                <strong>{{product.brand}}</strong>


                <hr>

                <br>


                <p> {{product.description}} </p>

                <div class="border">

                    <div class="col border-bottom">

                        <div class="row p-3">

                            <div class="col-6"> Price </div>

                            <div class="col-6 text-end"><span class="h4 fw-bold">$ {{product.price}}</span></div>

                        </div>

                    </div>

                    <div class="col">

                        <div class="row p-3">

                            <div class="col-6">


                                <label for="select">Qty</label>

                                &nbsp;

                                <select id="select">

                                    <option value="1">1</option>

                                    <option value="2">2</option>

                                    <option value="3">3</option>

                                    <option value="4">4</option>

                                </select>

                            </div>

                            <div class="col-6 text-end">

                                <button type="button" id="add-button" value="{{ product.id }}" class="btn btn-secondary btn-sm">

                                Add to cart

                                </button>


                            </div>

                        </div>

                    </div>

                </div>

            </div>

        </div>

    </main>

    <br>

</div>

<script>
    $(document).on('click', '#add-button', function(e){
        e.preventDefault();

        $.ajax({
            type: 'POST',
            url: '{% url "cart:add_to_cart" %}',
            data: {
                product_id: $('#add-button').val(),
                product_qty: $('#select option:selected').text(),
                csrfmiddlewaretoken: '{{ csrf_token }}',
                action: 'post'
            },
            success: function(response){
                document.getElementById('lblCartCount').textContent = response.qty
                const add_button = document.getElementById('add-button')
                add_button.disabled = true
                add_button.innerText = "Added to cart"
                add_button.className = "btn btn-success btn-sm"


            },
            error: function(error){
                console.log(error)
            }
        })

    })


</script>

{% endblock %}

bigcorp/shop/templates/shop/products.html
{% extends 'base.html' %}

{% load thumbnail %}

{% block content %}

 <!-- Introduction section -->
{% if not user.is_authenticated %}
<section class="py-4 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h4>Choose and it is in your hands.</h4>

        <br />

        <p class="lead text-muted">Browse and make the best deal</p>

        <br />

        <a href="{% url 'account:register' %}" class="btn btn-success my-2"> Create an account </a>
      </div>
    </div>
  </section>
{% endif %}
  <!-- All products section -->

  <section class="album py-5 bg-light">
    <div class="container">
      <div class="pb-3 h5">All products</div>

      <hr />

      <br />

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">

        {% for product in products %}
        <div class="col">
          <a class="text-black  text-decoration-none fs-4" href="{{product.get_absolute_url}}">
          <div class="card shadow-sm h-100">
            {% thumbnail product.image "300x300" as im %}
            <img class="img-fluid h-100" alt="Responsive image" src="{{ im.url }}" />
            {% endthumbnail %}
            <div class="card-body">
              <p class="card-text ">
                {{product.title|capfirst}}
              </p>
              <div class="d-flex justify-content-between align-items-center badge search-button text-wrap text-dark" style="width: 6rem;">
                <h5>$ {{product.price}}</h5>
              </div>
            </div>
          </div>
            </a>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
{% endblock %}